ALTER TABLE ACCOUNTREQUEST
MODIFY STATUS DEFAULT 'Entered';

CREATE SEQUENCE reqid_seq START WITH 1000 INCREMENT BY 10;
CREATE SEQUENCE accnt_seq START WITH 1;

ALTER TABLE ACCOUNTREQUEST
ADD CONSTRAINT ACCOUNTREQUEST_pk PRIMARY KEY (REQUESTID);

ALTER TABLE ACCOUNTREQUEST
ADD CONSTRAINT email_uk UNIQUE (email);

ALTER TABLE REGISTEREDINFO
ADD CONSTRAINT accountnumber_pk PRIMARY KEY (ACCOUNT_NUMBER);

ALTER TABLE REGISTEREDINFO
DROP COLUMN account_no;

CREATE TABLE LOGIN(
username VARCHAR2(10),
password VARCHAR2(20),
account_type VARCHAR(8)
);

CREATE OR REPLACE TRIGGER trg_ACCOUNTREQUEST
  BEFORE INSERT ON ACCOUNTREQUEST
  FOR EACH ROW
BEGIN
  :new.requestid := reqid_seq.nextval;
  :new.account_no := accnt_seq.nextval;
END;